# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: true
  timeout: 360
r: bioc-release
warnings_are_errors: false
after_success:
  - Rscript -e 'covr::codecov()'